language: java
services:
  - docker

script:
  - backend/gradlew build

before_deploy:
  - docker build -t ${DOCKER_USERNAME}/wootube:${DOCKER_IMAGE_VERSION} backend

deploy:
  - provider: script
    script: bash docker_push.sh
    on:
      branch: master
  - provider: script
    script: bash docker_push.sh
    on:
      branch: develop

branches:
  only:
    - master
    - "develop/*"