language: java
services:
  - docker

script:
  - backend/gradlew build

before_deploy:
  - docker build -t ${DOCKER_USERNAME}/wootube backend

deploy:
  - provider: script
    script: bash docker_push.sh latest
    on:
      branch: master
  - provider: script
    script: bash docker_push.sh dev
    on:
      branch: /dev/*/

branches:
  only:
    - master
    - /dev/*/
