language: java
services:
  - docker

script:
  - backend/gradlew build

before_deploy:
  - docker build -t wootube backend --build-arg JAR_NAME=$JAR_NAME JAR_PATH=$(find . find . -name $JAR_NAME)

deploy:
  # Deploy for production
  - provider: script
    script: bash docker_push.sh latest
    on:
      branch: master
  # Deploy for development
  - provider: script
    script: bash docker_push.sh dev
    on:
      branch: dev/ci-test
