language: java
services:
  - docker

script:
  - backend/gradlew build

before_deploy:
  - docker build -t ${DOCKER_USERNAME}/wootube backend

deploy:
  - provider: script
    script: bash docker_push.sh latest
    on:
      branch: master
  - provider: script
    script: bash docker_push.sh $TRAVIS_BRANCH
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ dev/ci-test

branches:
  only:
    - master
    - dev/ci-test
