language: java
services:
  - docker

script:
  - bash scripts/jar_build.sh

before_deploy:
  - bash scripts/docker_build.sh

deploy:
  # Deploy for production
  - provider: script
    script: bash scripts/docker_push.sh latest
    on:
      branch: master
  # Deploy for development
  - provider: script
    script: bash scripts/docker_push.sh dev
    on:
      branch: dev/ci-test
